# TODO: Translation updated at 2024-08-04 12:21

translate T_Chinese strings:

    # game/options.rpy:14
    old "Brief vom Himmel"
    new ""

    # game/options.rpy:30
    old "感谢曾为我作出指导的各位。（特别是那些能白嫖的网站）\n\n场景： {a=https://min-chi.material.jp/}みんちりえ{/a}\n\n立绘： {a=https://www.dlsite.com/home/circle/profile/=/maker_id/RG29527.html} 糖度70%{/a}\n\n{a=https://www.dlsite.com/home/circle/profile/=/maker_id/RG01014340.html}           ましろんショップ{/a}\n\n配乐： {a=https://kazuki-kaneko-music.com/}かねこかずき【kk】{/a}\n\n{a=https://www.dlsite.com/home/circle/profile/=/maker_id/RG47594.html}          Pastel Tone Music{/a}\n\n感谢名单： {a=https://space.bilibili.com/1733740438/}埋土的机械龙{/a}\n\n{a=https://space.bilibili.com/628485868/}           黑凤梨BlackPineappl{/a}\n\n{a=https://space.bilibili.com/378904108}            烈林凤{/a}\n\n{b}      以及官群，renpy中文空间论坛的大佬们。{/b}\n\n特别鸣谢： {a=https://space.bilibili.com/21792043}花间莉萝{/a}\n\n本人的启蒙书，引路人。\n\n主菜单插画： {a=https://www.pixiv.net/users/87833254}AutoINS{/a}\n\n作者的b站号： {a=https://b23.tv/dN9Bhix}YukiSoffd{/a}\n\n游戏群组： {a=https://discord.com/invite/KC4e6tsdJp}Discord{/a}\n\n{a=https://pd.qq.com/s/643oydoup}           QQ频道{/a}\n\n反馈请戳：↑ 或发送邮件至654952566@qq.com"
    new "感謝層為我作出指導的各位。（特別是那些能白嫖的網站）\n\n場景： {a=https://min-chi.material.jp/}みんちりえ{/a}\n\n立繪： {a=https://www.dlsite.com/home/circle/profile/=/maker_id/RG29527.html} 糖度70%{/a}\n\n{a=https://www.dlsite.com/home/circle/profile/=/maker_id/RG01014340.html}           ましろんショップ{/a}\n\n配樂： {a=https://kazuki-kaneko-music.com/}かねこかずき【kk】{/a}\n\n{a=https://www.dlsite.com/home/circle/profile/=/maker_id/RG47594.html}          Pastel Tone Music{/a}\n\n感謝名單： {a=https://space.bilibili.com/1733740438/}埋土的机械龙{/a}\n\n{a=https://space.bilibili.com/628485868/}           黑凤梨BlackPineappl{/a}\n\n{a=https://space.bilibili.com/378904108}            烈林凤{/a}\n\n{b}      以及官群，renpy中文空間論壇的大佬們。{/b}\n\n特別鳴謝： {a=https://space.bilibili.com/21792043}花间莉萝{/a}\n\n本人的啟蒙書，引路人。\n\n主菜單插畫： {a=https://www.pixiv.net/users/87833254}AutoINS{/a}\n\n作者的bilibili： {a=https://b23.tv/dN9Bhix}YukiSoffd{/a}\n\n遊戲群組： {a=https://discord.com/invite/KC4e6tsdJp}Discord{/a}\n\n{a=https://pd.qq.com/s/643oydoup}           QQ頻道{/a}\n\n反饋：↑ 或發送郵件至654952566@qq.com"